apiVersion: v1
kind: ServiceAccount
metadata:
  name: tailscale-outbound-proxy
  namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/component: tailscale-outbound-proxy
    app.kubernetes.io/name: tailscale-outbound-proxy
    app.kubernetes.io/part-of: tailscale-outbound-proxy
  name: tailscale-outbound-proxy-role
rules:
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - create
      - get
      - list
      - update
      - watch
      - patch
      - delete
  - apiGroups:
      - ""
    resources:
      - services
    verbs:
      - create
      - get
      - list
      - update
      - watch
      - patch
      - delete
  - apiGroups:
      - ""
    resources:
      - endpoints
    verbs:
      - get
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - get
  - apiGroups:
      - "apps"
    resources:
      - replicasets
    verbs:
      - get
  - apiGroups:
      - apps
    resources:
      - deployments
    verbs:
      - create
      - delete
      - get
      - list
      - update
      - watch
      - patch
  - apiGroups:
      - tsproxy.digizuite.com
    resources:
      - replacedservices
    verbs:
      - create
      - get
      - list
      - update
      - watch
      - patch
      - delete
  - apiGroups:
      - tsproxy.digizuite.com
    resources:
      - replacedservices/finalizers
    verbs:
      - update
      - patch
  - apiGroups:
      - tsproxy.digizuite.com
    resources:
      - replacedservices/status
    verbs:
      - get
      - update
      - patch
  - apiGroups:
      - keda.sh
    resources:
      - scaledobjects
    verbs:
      - create
      - get
      - list
      - update
      - watch
      - patch
      - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/component: tailscale-outbound-proxy
    app.kubernetes.io/name: tailscale-outbound-proxy
    app.kubernetes.io/part-of: tailscale-outbound-proxy
    servicebinding.io/controller: "true"
  name: tailscale-outbound-proxy-service-binding-role
  namespace: {{ .Release.Namespace }}
rules:
  - apiGroups:
      - tsproxy.digizuite.com
    resources:
      - replacedservices
    verbs:
      - get
      - list
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/component: tailscale-outbound-proxy
    app.kubernetes.io/name: tailscale-outbound-proxy
    app.kubernetes.io/part-of: tailscale-outbound-proxy
  name: tailscale-outbound-proxy-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: tailscale-outbound-proxy-role
subjects:
  - kind: ServiceAccount
    name: tailscale-outbound-proxy
    namespace: {{ .Release.Namespace }}
---
apiVersion: v1
kind: Secret
metadata:
  name: tailscale-outbound-proxy
  namespace: {{ .Release.Namespace }}
stringData:
  client_id: "{{ .Values.tailscale.client_id }}"
  client_secret: "{{ .Values.tailscale.client_secret }}"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tailscale-outbound-proxy
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/component: tailscale-outbound-proxy
    app.kubernetes.io/name: tailscale-outbound-proxy
    app.kubernetes.io/part-of: tailscale-outbound-proxy
spec:
  replicas: {{ .Values.operator.enable | ternary 1 0 }}
  selector:
    matchLabels:
      app.kubernetes.io/name: tailscale-outbound-proxy
  template:
    metadata:
      labels:
        app.kubernetes.io/component: tailscale-outbound-proxy
        app.kubernetes.io/name: tailscale-outbound-proxy
        app.kubernetes.io/part-of: tailscale-outbound-proxy
    spec:
      serviceAccountName: tailscale-outbound-proxy
      imagePullSecrets:
        - name: {{ .Values.operator.imagePullSecret }}
      containers:
        - name: operator
          image: {{ .Values.operator.image }}
          imagePullPolicy: {{ .Values.operator.imagePullPolicy }}
          env:
            - name: RUST_LOG
              value: "info"
            - name: TAILSCALE_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: tailscale-outbound-proxy
                  key: client_id
            - name: TAILSCALE_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: tailscale-outbound-proxy
                  key: client_secret
          resources:
            limits:
              cpu: {{ .Values.operator.resources.limits.cpu }}
              memory: {{ .Values.operator.resources.limits.memory }}
            requests:
              cpu: {{ .Values.operator.resources.requests.cpu }}
              memory: {{ .Values.operator.resources.requests.memory }}
      restartPolicy: Always
      nodeSelector:
        {{- toYaml .Values.operator.nodeSelector | nindent 8 }}
