operator:
  enable: true
  imagePullPolicy: Always
  image: digizuite.azurecr.io/digizuite/tailscale-outbound-proxy:master
  imagePullSecret: ""
  resources:
    limits:
      cpu: 100m
      memory: 200Mi
    requests:
      cpu: 100m
      memory: 200Mi
  nodeSelector: {}
tailscale:
  client_id: ""
  client_secret: ""